#!/usr/bin/env python3
"""Assemble wp-content/plugins/conexao-blog-translation/includes/translation-map.php

Inputs
  stage5-work/en/<pt_slug>.json      — human translations (one per post)
  stage5-work/source/<pt_slug>.json  — PT REST payloads

The posts page copy and the category term map are authored here (small, and they
must stay in sync with the Stage 4.5 page translation of the Blog page).
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(
    HERE, "..", "wp-content", "plugins", "conexao-blog-translation",
    "includes", "translation-map.php",
)

POSTS_PAGE = {
    "slug": "blog",
    "title": "Blog",
    "content": "<!-- wp:paragraph --><p>Articles and news for the Brazilian "
               "community in Ireland: health and wellbeing, entrepreneurship, "
               "recipes, training and life far from home.</p><!-- /wp:paragraph -->",
    "meta_desc": "The Conexão BR Irlanda blog — articles, news and information "
                 "for Brazilians in Ireland.",
}

TERMS = {
    "saude-e-bem-estar": {
        "name": "Health & Wellbeing",
        "slug": "health-and-wellbeing",
        "description": "Articles on health, wellbeing, self-care and mental "
                       "health for Brazilians in Ireland.",
    },
    "empreendedor": {
        "name": "Entrepreneurship",
        "slug": "entrepreneurship",
        "description": "Articles for Brazilian entrepreneurs and small business "
                       "owners in Ireland.",
    },
    "receitas": {
        "name": "Recipes",
        "slug": "recipes",
        "description": "Recipes and cooking ideas from the Brazilian community "
                       "in Ireland.",
    },
    "lazer": {
        "name": "Leisure",
        "slug": "leisure",
        "description": "Leisure and tourism ideas in Ireland.",
    },
    "capacitacao": {
        "name": "Training",
        "slug": "training",
        "description": "Training, courses and upskilling opportunities in Ireland.",
    },
}


def php_str(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"

def main():
    en_files = sorted(glob.glob(os.path.join(HERE, "en", "*.json")))
    if not en_files:
        sys.exit("no translated posts found in stage5-work/en/")

    posts = []
    missing_source = []
    for path in en_files:
        data = json.load(open(path, encoding="utf-8"))
        pt_slug = data["pt_slug"]
        if not os.path.exists(os.path.join(HERE, "source", pt_slug + ".json")):
            missing_source.append(pt_slug)
        for key in ("pt_slug", "en_slug", "en_title", "en_excerpt",
                    "en_meta_description", "en_content"):
            if not data.get(key):
                sys.exit(f"{pt_slug}: empty field {key}")

        links = []
        for rule in (data.get("link_map") or []):
            links.append(
                "{ 'from' => " + php_str(rule["from"]) + ", "
                "'to_pt_post_slug' => " + php_str(rule["to_pt_post_slug"]) + " }"
            )
        link_php = "array( " + ", ".join(links) + " )" if links else "array()"

        posts.append("\n".join([
            "\t\t" + php_str(pt_slug) + " => array(",
            "\t\t\t'en_slug'             => " + php_str(data["en_slug"]) + ",",
            "\t\t\t'en_title'            => " + php_str(data["en_title"]) + ",",
            "\t\t\t'en_excerpt'          => " + php_str(data["en_excerpt"]) + ",",
            "\t\t\t'en_meta_description' => " + php_str(data["en_meta_description"]) + ",",
            "\t\t\t'en_content'          => " + php_str(data["en_content"]) + ",",
            "\t\t\t'link_map'            => " + link_php + ",",
            "\t\t),",
        ]))

    terms = []
    for slug, term in TERMS.items():
        terms.append(
            "\t\t" + php_str(slug) + " => array(\n"
            "\t\t\t'name'        => " + php_str(term["name"]) + ",\n"
            "\t\t\t'slug'        => " + php_str(term["slug"]) + ",\n"
            "\t\t\t'description' => " + php_str(term["description"]) + ",\n"
            "\t\t),"
        )

    header = '''<?php
/**
 * Stage 5 — authored English Blog content.
 *
 * ONE entry per Portuguese blog post, keyed by its Portuguese slug (the stable,
 * portable identity — never a local post ID, per the project architecture
 * rules). Bodies are human-authored English translations that preserve the
 * source HTML structure, media and external links; `link_map` carries the only
 * links that must be re-pointed at an English destination (resolved through the
 * Polylang relationship at import time).
 *
 * Generated by stage5-work/build-manifest.py — do not hand-edit the
 * `posts` block; edits belong in the per-post JSON sources.
 *
 * @package Conexao_Blog_Translation
 */

if ( ! defined( 'ABSPATH' ) ) {
\texit;
}

/**
 * The authored EN Blog translation manifest.
 *
 * @return array{source:string,posts_page:array,terms:array,posts:array,excluded:array}
 */
function conexao_blog_translation_manifest(): array {
\tstatic $manifest = null;

\tif ( null !== $manifest ) {
\t\treturn $manifest;
\t}

\t$manifest = array(
\t\t'source'     => %s,
\t\t'posts_page' => array(
\t\t\t'slug'      => %s,
\t\t\t'title'     => %s,
\t\t\t'content'   => %s,
\t\t\t'meta_desc' => %s,
\t\t),
\t\t'terms'      => array(
%s
\t\t),
\t\t'posts'      => array(
%s
\t\t),
\t\t// Documented exclusions: none. Every public blog post is translated.
\t\t'excluded'   => array(),
\t);

\treturn $manifest;
}
''' % (
        php_str('https://conexaobr.ie/ Blog — public REST inventory + human English translations.'),
        php_str(POSTS_PAGE["slug"]),
        php_str(POSTS_PAGE["title"]),
        php_str(POSTS_PAGE["content"]),
        php_str(POSTS_PAGE["meta_desc"]),
        "\n".join(terms),
        "\n".join(posts),
    )

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(header)

    print(f"wrote {OUT} with {len(posts)} posts, {len(terms)} terms")
    if missing_source:
        print("WARNING: no PT source payload for: " + ", ".join(missing_source))

    slugs = {}
    for path in en_files:
        data = json.load(open(path, encoding="utf-8"))
        slugs.setdefault(data["en_slug"], []).append(data["pt_slug"])
    dupes = {k: v for k, v in slugs.items() if len(v) > 1}
    if dupes:
        sys.exit(f"duplicate EN slugs: {dupes}")


if __name__ == "__main__":
    main()
