<?php
/**
 * One-time metadata fix: correct Wikimedia Commons source URLs on leisure posts.
 *
 * Bug: Conexao_Wikimedia_Client::file_page_url() previously built Commons file
 * page URLs from the API endpoint base, producing invalid URLs like:
 *
 *   https://commons.wikimedia.org/w/api.php/File:<filename>
 *
 * Correct Commons file page URLs use the public wiki base:
 *
 *   https://commons.wikimedia.org/wiki/File:<filename>
 *
 * This script:
 *   1. Finds ONLY leisure posts whose `_leisure_image_source_url` value starts
 *      with the exact broken prefix produced by the old URL builder.
 *   2. Deterministically rewrites that prefix to `/wiki/File:` (the filename
 *      part is preserved byte-for-byte; no Wikimedia API calls are made).
 *   3. Leaves every other meta value (license, author, attribution, attachment,
 *      image URL, alt text, status) untouched.
 *
 * The operation is idempotent: correct URLs (/wiki/File: or any other source
 * URL) are never matched, so re-running makes zero changes.
 *
 * Run via (inside Docker):
 *   docker compose exec wordpress wp eval-file \
 *     /var/www/html/wp-content/plugins/../scripts/fix-wikimedia-source-urls.php \
 *     --dry-run          # preview only
 *
 *   docker compose exec wordpress wp eval-file \
 *     /var/www/html/wp-content/plugins/../scripts/fix-wikimedia-source-urls.php
 *
 * @package Conexao_BR_Irlanda
 */

// --- WordPress bootstrap (same pattern as other seed/migration scripts) ---
require_once __DIR__ . '/lib/bootstrap.php';
conexao_script_load_wordpress();

// Only allow admins (WP-CLI or CLI runs are trusted maintenance contexts;
// browser access requires manage_options).
$is_cli_run = ( php_sapi_name() === 'cli' ) || ( defined( 'WP_CLI' ) && WP_CLI );
if ( ! $is_cli_run && ! current_user_can( 'manage_options' ) ) {
	die( 'Unauthorized access' );
}

// --- Configuration ---
// Exact prefix produced by the old, broken file_page_url() implementation.
// Matching on this exact prefix guarantees only records generated by the bug
// are corrected; unrelated or already-correct URLs never match.
$broken_prefix = 'https://commons.wikimedia.org/w/api.php/File:';
$fixed_prefix  = 'https://commons.wikimedia.org/wiki/File:';

// --- Parse CLI arguments ---
$is_cli  = ( php_sapi_name() === 'cli' );
$args    = $is_cli ? getopt( '', array( 'dry-run' ) ) : array();
$dry_run = isset( $args['dry-run'] );

// --- Find affected records ---
// Query the meta table directly so we only touch records that carry a URL with
// the exact broken prefix, regardless of post type (the meta key is used by
// leisure posts AND their imported Media Library attachments).
global $wpdb;
$post_ids = $wpdb->get_col( $wpdb->prepare(
	"SELECT DISTINCT post_id FROM {$wpdb->postmeta}
	 WHERE meta_key = '_leisure_image_source_url' AND meta_value LIKE %s",
	$wpdb->esc_like( $broken_prefix ) . '%'
) );
$post_ids = array_map( 'intval', (array) $post_ids );

echo "=== Wikimedia source URL fix ===\n";
echo "Broken prefix: {$broken_prefix}\n";
echo "Fixed prefix:  {$fixed_prefix}\n";

if ( empty( $post_ids ) ) {
	echo "No records with the broken URL pattern found. Nothing to do.\n";
	exit( 0 );
}

echo sprintf( "Found %d record(s) with a broken source URL.\n\n", count( $post_ids ) );

$fixed = 0;
foreach ( $post_ids as $post_id ) {
	$old_url = (string) get_post_meta( $post_id, '_leisure_image_source_url', true );

	// Defensive: only rewrite when the value actually starts with the exact
	// broken prefix (idempotency + no unrelated URL is ever modified).
	if ( 0 !== strpos( $old_url, $broken_prefix ) ) {
		continue;
	}

	// Deterministic prefix swap; the filename part is untouched.
	$new_url = $fixed_prefix . substr( $old_url, strlen( $broken_prefix ) );

	// Validate/escape using existing conventions before saving.
	$new_url = esc_url_raw( $new_url );

	if ( '' === $new_url ) {
		echo sprintf( "  SKIP post %d — corrected URL failed esc_url_raw validation.\n", $post_id );
		continue;
	}

	if ( $dry_run ) {
		echo sprintf( "  [DRY RUN] post %d:\n    OLD: %s\n    NEW: %s\n", $post_id, $old_url, $new_url );
		continue;
	}

	update_post_meta( $post_id, '_leisure_image_source_url', $new_url );
	$fixed++;
	echo sprintf( "  FIXED post %d:\n    OLD: %s\n    NEW: %s\n", $post_id, $old_url, $new_url );
}

// --- Summary ---
echo "\n=== Summary ===\n";
echo sprintf( "Posts matched: %d\n", count( $post_ids ) );
echo sprintf( "URLs corrected: %d\n", $dry_run ? 0 : $fixed );
if ( $dry_run ) {
	echo "\n[DRY RUN] No changes were made. Re-run without --dry-run to apply.\n";
} else {
	echo "\nDone. Re-running this script is safe (it is idempotent).\n";
}
